/**
 * @file    spi.h
 * @brief   Universal SPI (Serial Peripheral Interface) Driver Library
 * @version 1.0.0
 * @date    2024
 *
 * ============================================================================
 *                        SPI PROTOCOL OVERVIEW
 * ============================================================================
 *
 * SPI (Serial Peripheral Interface) is a synchronous, full-duplex, master-slave
 * serial communication protocol developed by Motorola in the mid-1980s.
 * It is the dominant protocol for high-speed embedded peripheral communication.
 *
 * PHYSICAL BUS — 4 wires:
 *   MOSI : Master Out Slave In   — data FROM master TO slave
 *   MISO : Master In Slave Out   — data FROM slave TO master
 *   SCK  : Serial Clock          — always generated by master
 *   CS   : Chip Select (active LOW) — selects which slave is active
 *
 * Unlike I2C, SPI has NO pull-up resistors and NO addressing.
 * Each slave device needs its own dedicated CS pin on the master.
 *
 *              MASTER
 *           ┌──────────┐
 *      MOSI─┤          ├─MOSI──── SLAVE1
 *      MISO─┤          ├─MISO──── SLAVE1
 *       SCK─┤          ├─SCK───── SLAVE1
 *       CS0─┤          ├─CS────── SLAVE1
 *       CS1─┤          ├──────────────── SLAVE2 CS
 *           └──────────┘
 *
 * FULL-DUPLEX:
 *   Master sends 1 byte on MOSI while simultaneously receiving 1 byte on MISO.
 *   Both happen in the SAME clock cycle. This is a fundamental difference from I2C.
 *
 * ============================================================================
 *                        SPI CLOCK MODES (CPOL / CPHA)
 * ============================================================================
 *
 * Every SPI device has a required clock mode. Using the wrong mode = garbled data.
 * Check the device datasheet for "SPI Mode" or "CPOL/CPHA" in the timing section.
 *
 *  CPOL (Clock Polarity): idle state of SCK
 *    0 = SCK idles LOW
 *    1 = SCK idles HIGH
 *
 *  CPHA (Clock Phase): when data is sampled
 *    0 = data sampled on LEADING  edge (first edge)
 *    1 = data sampled on TRAILING edge (second edge)
 *
 *  ┌──────┬──────┬──────┬───────────────────────────────────────────────┐
 *  │ Mode │ CPOL │ CPHA │ Common devices                                │
 *  ├──────┼──────┼──────┼───────────────────────────────────────────────┤
 *  │  0   │  0   │  0   │ W25Qxx Flash, MCP3204 ADC, SD cards           │
 *  │  1   │  0   │  1   │ MAX31855 thermocouple, some DACs              │
 *  │  2   │  1   │  0   │ Some sensors, rare                            │
 *  │  3   │  1   │  1   │ ST7735 TFT display, some ADCs                 │
 *  └──────┴──────┴──────┴───────────────────────────────────────────────┘
 *
 * MODE 0 timing (most common):
 *   SCK: ____/‾\_/‾\_/‾\_/‾\_/‾\_/‾\_/‾\_/‾\____
 *  MOSI: ═══[b7][b6][b5][b4][b3][b2][b1][b0]═══
 *  MISO: ═══[b7][b6][b5][b4][b3][b2][b1][b0]═══
 *    CS: ‾‾‾\___________________________________/‾
 *           ^ CS LOW (select)        CS HIGH ^ (deselect)
 *
 * ============================================================================
 *                        TRANSACTION STRUCTURE
 * ============================================================================
 *
 *  A typical SPI transaction:
 *    1. Pull CS LOW  (assert chip select)
 *    2. Transfer N bytes (MOSI out, MISO in simultaneously)
 *    3. Pull CS HIGH (deselect — ends transaction)
 *
 *  For devices with command + data structure (most flash, displays):
 *    CS LOW → send command byte → send/recv data bytes → CS HIGH
 *
 *  For read-only devices (thermocouples, some ADCs):
 *    CS LOW → clock out dummy bytes (0x00) → receive data on MISO → CS HIGH
 *
 * ============================================================================
 *                        REAL-WORLD USAGE (2024)
 * ============================================================================
 *
 *  [STORAGE & MEMORY]
 *   - W25Q128 / W25Q256 : NOR Flash (firmware storage, data logging)
 *     → Used in: ESP32 modules, STM32 boards, IoT devices, routers
 *   - AT45DB / S25FL     : DataFlash (high-endurance logging)
 *   - FRAM (MB85RS)      : Ferroelectric RAM (industrial logging, no wear)
 *   - SD / microSD cards : Mass storage (FAT32 over SPI mode)
 *     → Used in: data loggers, cameras, Raspberry Pi boot storage
 *
 *  [SENSORS & MEASUREMENT]
 *   - MAX31855 / MAX31865 : Thermocouple/RTD amplifier (industrial temperature)
 *     → Used in: 3D printers (hotend), industrial ovens, HVAC
 *   - MCP3204 / ADS1256   : High-resolution ADC (precision measurement)
 *     → Used in: oscilloscopes, data acquisition, audio
 *   - ICM-42688-P         : High-end IMU (aerospace, precision drones)
 *   - BMP388              : Barometric pressure (altimeters, weather)
 *   - LIS3DSH             : Accelerometer (ST eval boards, wearables)
 *   - ADXL345             : Accelerometer (tilt sensing, impact detection)
 *
 *  [DISPLAYS]
 *   - ST7735 / ST7789     : Color TFT LCD controller (small embedded displays)
 *     → Used in: smartwatches, handheld instruments, IoT dashboards
 *   - ILI9341 / ILI9488  : 320×240 / 480×320 TFT (mid-size displays)
 *     → Used in: GPS units, medical monitors, industrial HMI
 *   - SSD1351             : OLED color display (high contrast wearables)
 *   - MAX7219             : LED matrix/7-seg driver (scoreboards, clocks)
 *   - e-Paper / e-Ink     : Low-power bistable displays (price tags, badges)
 *
 *  [POWER & CONVERSION]
 *   - MCP4921 / DAC8551   : 12-bit DAC (waveform gen, voltage reference)
 *   - ADE7758             : Energy metering IC (smart power meters)
 *   - LTC2943             : Battery fuel gauge (industrial battery packs)
 *
 *  [WIRELESS & NETWORKING]
 *   - CC1101 / RFM69      : Sub-GHz RF transceiver (LoRa, 433MHz remotes)
 *   - W5500               : Ethernet controller (embedded web servers)
 *   - ENC28J60            : Ethernet (Arduino Ethernet shield)
 *   - nRF24L01            : 2.4GHz RF (RC controllers, wireless sensors)
 *
 *  [AUTOMOTIVE (AEC-Q100)]
 *   - MCP2515             : CAN bus controller (vehicle OBD, industrial CAN)
 *   - TLE5009             : GMR angle sensor (electric power steering)
 *   - TPIC6C595           : Power shift register (automotive lighting)
 *
 *  [CONSUMER ELECTRONICS]
 *   - SPI Flash in every WiFi router (firmware storage)
 *   - SPI in every smartphone (NOR flash for bootloader)
 *   - FPGA configuration via SPI
 *   - SPI in hard drives (internal config flash)
 *
 * ============================================================================
 *                        SPI vs I2C — WHEN TO USE WHICH
 * ============================================================================
 *
 *  Use SPI when:
 *   - Speed matters (SPI: 50+ MHz, I2C: max 3.4 MHz)
 *   - Full-duplex simultaneous TX/RX needed
 *   - Connecting displays or large flash memories
 *   - Long wire runs (SPI has better noise immunity at speed)
 *
 *  Use I2C when:
 *   - Minimizing wire count (only 2 wires vs 4)
 *   - Connecting many low-speed sensors on one bus
 *   - GPIO pins are scarce
 *
 * ============================================================================
 *                        IMPROVEMENTS OVER i2c_lib
 * ============================================================================
 *
 *  This library improves on the i2c_lib design in the following ways:
 *
 *  1. TYPED TRANSFER FUNCTIONS
 *     i2c_lib used raw uint8_t* everywhere.
 *     spi_lib adds spi_transfer8(), spi_transfer16(), spi_transfer32()
 *     for common word sizes — no manual byte-packing needed.
 *
 *  2. DMA-READY STRUCTURE
 *     Transfer descriptors (spi_xfer_t) separate the "what to transfer"
 *     from the "how to transfer" — makes adding DMA trivial later.
 *
 *  3. TRANSACTION OBJECT
 *     spi_transaction_begin() / spi_transaction_end() wrap CS control
 *     explicitly, preventing half-open transactions on error paths.
 *
 *  4. DEVICE HANDLE WITH CONFIG
 *     Each device (spi_device_t) stores its own CS pin, mode, speed,
 *     and bit order. Switching between two devices on the same bus
 *     automatically reconfigures the bus — no manual mode switching.
 *
 *  5. COMPILE-TIME ASSERTIONS
 *     Static asserts on struct sizes and config values catch
 *     misconfiguration at build time, not runtime.
 *
 *  6. CONST-CORRECT API
 *     All read-only pointer parameters are marked const throughout.
 *
 * @author  SPI Library Contributors
 * @license MIT License
 */

#ifndef SPI_H
#define SPI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ============================================================================
 * VERSION
 * ========================================================================== */

#define SPI_LIB_VERSION_MAJOR   1
#define SPI_LIB_VERSION_MINOR   0
#define SPI_LIB_VERSION_PATCH   0
#define SPI_LIB_VERSION_STRING  "1.0.0"

/* ============================================================================
 * CONFIGURATION — override in spi_config.h before including this file
 * ========================================================================== */

#ifndef SPI_MAX_BUSES
  #define SPI_MAX_BUSES           4       /**< Max simultaneous SPI bus instances */
#endif

#ifndef SPI_MAX_DEVICES_PER_BUS
  #define SPI_MAX_DEVICES_PER_BUS 8       /**< Max devices registered on one bus */
#endif

#ifndef SPI_TIMEOUT_DEFAULT_MS
  #define SPI_TIMEOUT_DEFAULT_MS  100     /**< Default per-transfer timeout (ms) */
#endif

#ifndef SPI_TX_BUFFER_SIZE
  #define SPI_TX_BUFFER_SIZE      512     /**< Software TX staging buffer (bytes) */
#endif

#ifndef SPI_RX_BUFFER_SIZE
  #define SPI_RX_BUFFER_SIZE      512     /**< Software RX staging buffer (bytes) */
#endif

#ifndef SPI_ENABLE_RTOS
  #define SPI_ENABLE_RTOS         0       /**< Enable FreeRTOS mutex protection */
#endif

#ifndef SPI_ENABLE_DMA
  #define SPI_ENABLE_DMA          0       /**< Enable DMA transfer support */
#endif

/* ============================================================================
 * ERROR CODES
 * ========================================================================== */

/**
 * @brief SPI operation error codes
 *
 * All API functions return spi_err_t. Always check the return value.
 */
typedef enum {
    SPI_OK              =  0,   /**< Success */
    SPI_ERR_INVALID_ARG = -1,   /**< NULL pointer or bad argument */
    SPI_ERR_NOT_INIT    = -2,   /**< spi_init() not called */
    SPI_ERR_BUS_BUSY    = -3,   /**< Another transfer in progress */
    SPI_ERR_TIMEOUT     = -4,   /**< Transfer timed out */
    SPI_ERR_OVERFLOW    = -5,   /**< Transfer length exceeds buffer */
    SPI_ERR_PLATFORM    = -6,   /**< Platform HAL error */
    SPI_ERR_NO_DEVICE   = -7,   /**< Device handle not registered */
    SPI_ERR_DMA         = -8,   /**< DMA error */
    SPI_ERR_MODE        = -9,   /**< Unsupported clock mode */
} spi_err_t;

/* ============================================================================
 * ENUMERATIONS
 * ========================================================================== */

/**
 * @brief SPI clock mode (CPOL + CPHA combined)
 *
 * CRITICAL: Every SPI device requires a specific mode.
 * Using the wrong mode produces garbled data with no error indication.
 * Always check the device datasheet "SPI timing" or "CPOL/CPHA" section.
 *
 *  Mode 0 (CPOL=0, CPHA=0): SCK idle LOW,  sample on rising  edge — MOST COMMON
 *  Mode 1 (CPOL=0, CPHA=1): SCK idle LOW,  sample on falling edge
 *  Mode 2 (CPOL=1, CPHA=0): SCK idle HIGH, sample on falling edge
 *  Mode 3 (CPOL=1, CPHA=1): SCK idle HIGH, sample on rising  edge
 */
typedef enum {
    SPI_MODE_0 = 0,     /**< CPOL=0 CPHA=0 — W25Q128, MCP3204, SD card */
    SPI_MODE_1 = 1,     /**< CPOL=0 CPHA=1 — MAX31855, MAX31865 */
    SPI_MODE_2 = 2,     /**< CPOL=1 CPHA=0 — rare */
    SPI_MODE_3 = 3,     /**< CPOL=1 CPHA=1 — ST7735, ST7789, ILI9341 */
} spi_mode_t;

/**
 * @brief Bit transmission order
 */
typedef enum {
    SPI_BITORDER_MSB_FIRST = 0,     /**< MSB sent first — standard (most devices) */
    SPI_BITORDER_LSB_FIRST = 1,     /**< LSB sent first — some shift registers */
} spi_bitorder_t;

/**
 * @brief CS (Chip Select) polarity
 */
typedef enum {
    SPI_CS_ACTIVE_LOW  = 0,     /**< CS LOW = selected (standard) */
    SPI_CS_ACTIVE_HIGH = 1,     /**< CS HIGH = selected (rare, some DACs) */
} spi_cs_polarity_t;

/**
 * @brief Driver type
 */
typedef enum {
    SPI_MODE_HARDWARE = 0,      /**< Hardware SPI peripheral */
    SPI_MODE_SOFTWARE = 1,      /**< Software bit-bang on GPIO */
} spi_driver_t;

/**
 * @brief Bus state
 */
typedef enum {
    SPI_STATE_IDLE      = 0,
    SPI_STATE_BUSY      = 1,
    SPI_STATE_ERROR     = 2,
} spi_state_t;

/* ============================================================================
 * STRUCTURES
 * ========================================================================== */

/**
 * @brief Platform HAL callbacks
 *
 * Implement these 6 functions for your target platform, then pass
 * a pointer to this struct in spi_config_t.
 *
 * For hardware SPI, only cs_write + millis are needed (the peripheral
 * handles MOSI/MISO/SCK automatically).
 */
typedef struct {
    /** Set MOSI pin level (software mode only) */
    void     (*mosi_write)(bool level, void *ctx);

    /** Read MISO pin level (software mode only) */
    bool     (*miso_read)(void *ctx);

    /** Set SCK pin level (software mode only) */
    void     (*sck_write)(bool level, void *ctx);

    /**
     * @brief Set CS pin level
     * @param cs_id   Which CS pin (0 = first device, 1 = second, etc.)
     * @param level   true = HIGH, false = LOW
     * @param ctx     User context
     *
     * NOTE: This is called for EVERY device — use cs_id to select the
     * correct GPIO pin for multi-device buses.
     */
    void     (*cs_write)(uint8_t cs_id, bool level, void *ctx);

    /** Delay in microseconds */
    void     (*delay_us)(uint32_t us);

    /** Millisecond monotonic timestamp (for timeouts) */
    uint32_t (*millis)(void);

    /** User context pointer passed to all callbacks */
    void *user_ctx;
} spi_hal_t;

/**
 * @brief Per-device configuration
 *
 * Each device on the bus has its own config — different clock speed,
 * SPI mode, CS pin, and bit order are all supported simultaneously.
 *
 * @example
 * @code
 * spi_device_cfg_t flash_cfg = {
 *     .cs_id      = 0,
 *     .mode       = SPI_MODE_0,
 *     .speed_hz   = 40000000,   // 40 MHz
 *     .bit_order  = SPI_BITORDER_MSB_FIRST,
 *     .cs_pol     = SPI_CS_ACTIVE_LOW,
 *     .cs_setup_ns = 100,       // 100ns CS-to-SCK setup time
 *     .cs_hold_ns  = 100,       // 100ns SCK-to-CS hold time
 * };
 * @endcode
 */
typedef struct {
    uint8_t           cs_id;        /**< CS pin identifier (passed to hal.cs_write) */
    spi_mode_t        mode;         /**< Clock mode (CPOL/CPHA) */
    uint32_t          speed_hz;     /**< Clock frequency in Hz */
    spi_bitorder_t    bit_order;    /**< MSB or LSB first */
    spi_cs_polarity_t cs_pol;       /**< CS active LOW (default) or HIGH */
    uint32_t          cs_setup_ns;  /**< CS assert-to-SCK delay (nanoseconds) */
    uint32_t          cs_hold_ns;   /**< Last SCK-to-CS-deassert delay (ns) */
} spi_device_cfg_t;

/**
 * @brief Bus-level configuration
 */
typedef struct {
    spi_driver_t    driver;         /**< Hardware or software */
    uint8_t         hw_instance;    /**< Hardware SPI index (0=SPI1, 1=SPI2...) */
    uint32_t        timeout_ms;     /**< Default timeout, 0 = use default */
    spi_hal_t      *hal;            /**< HAL callbacks (required) */
} spi_config_t;

/**
 * @brief Transfer statistics
 */
typedef struct {
    uint32_t tx_bytes;          /**< Total bytes sent */
    uint32_t rx_bytes;          /**< Total bytes received */
    uint32_t transfers;         /**< Completed transfers */
    uint32_t errors;            /**< Error count */
    uint32_t timeouts;          /**< Timeout count */
    uint32_t cs_toggles;        /**< CS assert/deassert cycles */
} spi_stats_t;

/**
 * @brief Transfer descriptor — separates "what" from "how"
 *
 * Improvement over i2c_lib: having a descriptor struct makes it trivial
 * to add DMA support later — just pass the descriptor to the DMA engine.
 */
typedef struct {
    const uint8_t  *tx_buf;     /**< Data to transmit (NULL = send 0x00) */
    uint8_t        *rx_buf;     /**< Buffer for received data (NULL = discard) */
    size_t          len;        /**< Number of bytes to transfer */
} spi_xfer_t;

/**
 * @brief SPI bus handle (opaque)
 */
typedef struct spi_bus_s *spi_bus_t;

/**
 * @brief SPI device handle (opaque)
 *
 * Improvement over i2c_lib: devices are registered on the bus,
 * storing their config. Bus reconfigures automatically on device switch.
 */
typedef struct spi_device_s *spi_device_t;

/* ============================================================================
 * BUS INITIALIZATION
 * ========================================================================== */

/**
 * @brief Initialize an SPI bus
 *
 * @param[out] bus  Pointer to receive bus handle
 * @param[in]  cfg  Bus configuration
 * @return SPI_OK on success
 *
 * @example
 * @code
 * spi_bus_t bus;
 * spi_config_t cfg = {
 *     .driver     = SPI_MODE_SOFTWARE,
 *     .timeout_ms = 50,
 *     .hal        = &my_hal,
 * };
 * spi_init(&bus, &cfg);
 * @endcode
 */
spi_err_t spi_init(spi_bus_t *bus, const spi_config_t *cfg);

/**
 * @brief De-initialize an SPI bus and release all resources
 *
 * @param bus  Bus handle
 * @return SPI_OK on success
 */
spi_err_t spi_deinit(spi_bus_t bus);

/* ============================================================================
 * DEVICE REGISTRATION
 * ========================================================================== */

/**
 * @brief Register a device on the bus
 *
 * IMPROVEMENT OVER i2c_lib: Devices are registered with their own config.
 * The bus automatically switches mode/speed when a different device is selected.
 * No manual reconfiguration needed between device transfers.
 *
 * @param bus          Bus handle
 * @param[in]  dev_cfg Device-specific configuration
 * @param[out] device  Pointer to receive device handle
 * @return SPI_OK on success
 *
 * @example
 * @code
 * spi_device_t flash;
 * spi_device_cfg_t cfg = {
 *     .cs_id    = 0,
 *     .mode     = SPI_MODE_0,
 *     .speed_hz = 40000000,
 * };
 * spi_register_device(bus, &cfg, &flash);
 * @endcode
 */
spi_err_t spi_register_device(spi_bus_t bus, const spi_device_cfg_t *dev_cfg,
                               spi_device_t *device);

/* ============================================================================
 * TRANSACTION CONTROL
 *
 * IMPROVEMENT OVER i2c_lib: Explicit begin/end transaction functions
 * make CS control clear and prevent half-open transactions on error.
 * ========================================================================== */

/**
 * @brief Assert CS and begin a transaction with a device
 *
 * Pulls CS LOW (or HIGH if cs_pol = ACTIVE_HIGH), applies cs_setup_ns delay.
 * All transfers between begin and end share the same CS assertion.
 *
 * @param device  Device handle
 * @return SPI_OK on success
 */
spi_err_t spi_transaction_begin(spi_device_t device);

/**
 * @brief End transaction and deassert CS
 *
 * Applies cs_hold_ns delay, then releases CS.
 * Always call this — even on error paths — to prevent bus lockup.
 *
 * @param device  Device handle
 * @return SPI_OK on success
 */
spi_err_t spi_transaction_end(spi_device_t device);

/* ============================================================================
 * CORE TRANSFER FUNCTIONS
 * ========================================================================== */

/**
 * @brief Full-duplex transfer: send and receive simultaneously
 *
 * The fundamental SPI operation. For every byte sent on MOSI, one byte
 * is received on MISO at exactly the same time.
 *
 * Must be called between spi_transaction_begin() and spi_transaction_end().
 *
 * @param device  Device handle
 * @param xfer    Transfer descriptor (tx_buf, rx_buf, len)
 * @return SPI_OK on success
 *
 * @example
 * @code
 * uint8_t tx[] = { 0x03, 0x00, 0x10, 0x00 };  // READ command + 24-bit addr
 * uint8_t rx[4];
 * spi_xfer_t xfer = { .tx_buf = tx, .rx_buf = rx, .len = 4 };
 * spi_transaction_begin(flash);
 * spi_transfer(flash, &xfer);
 * spi_transaction_end(flash);
 * @endcode
 */
spi_err_t spi_transfer(spi_device_t device, const spi_xfer_t *xfer);

/**
 * @brief Transmit only — discard received bytes
 *
 * Convenience wrapper: sends data and ignores MISO.
 * Used for commands, display pixel data, register writes.
 *
 * @param device  Device handle
 * @param data    Buffer to transmit
 * @param len     Number of bytes
 * @return SPI_OK on success
 */
spi_err_t spi_write(spi_device_t device, const uint8_t *data, size_t len);

/**
 * @brief Receive only — transmit 0x00 bytes on MOSI
 *
 * Convenience wrapper: clocks out dummy bytes to receive from slave.
 * Used for ADC reads, thermocouple reads, status register reads.
 *
 * @param device  Device handle
 * @param data    Buffer to store received bytes
 * @param len     Number of bytes to receive
 * @return SPI_OK on success
 */
spi_err_t spi_read(spi_device_t device, uint8_t *data, size_t len);

/* ============================================================================
 * TYPED TRANSFER FUNCTIONS
 * IMPROVEMENT OVER i2c_lib: typed functions for common word sizes.
 * Eliminates manual byte-packing/unpacking in driver code.
 * ========================================================================== */

/**
 * @brief Transfer a single byte and return the received byte
 *
 * @param device    Device handle
 * @param tx_byte   Byte to send
 * @param[out] rx   Received byte (NULL to discard)
 * @return SPI_OK on success
 *
 * @example
 * @code
 * // Read W25Q128 status register
 * uint8_t status;
 * spi_transaction_begin(flash);
 * spi_transfer8(flash, 0x05, NULL);   // send RDSR command
 * spi_transfer8(flash, 0x00, &status); // read response
 * spi_transaction_end(flash);
 * @endcode
 */
spi_err_t spi_transfer8(spi_device_t device, uint8_t tx_byte, uint8_t *rx);

/**
 * @brief Transfer a 16-bit word (big-endian on wire)
 *
 * Sends MSB first. Commonly used for 12-bit ADC reads (MCP3204)
 * and 16-bit display commands (ST7735).
 *
 * @param device    Device handle
 * @param tx_word   16-bit value to send
 * @param[out] rx   Received 16-bit value (NULL to discard)
 * @return SPI_OK on success
 */
spi_err_t spi_transfer16(spi_device_t device, uint16_t tx_word, uint16_t *rx);

/**
 * @brief Transfer a 32-bit word (big-endian on wire)
 *
 * Used for thermocouple reads (MAX31855 returns 32-bit frame),
 * and 32-bit flash operations.
 *
 * @param device    Device handle
 * @param tx_word   32-bit value to send
 * @param[out] rx   Received 32-bit value (NULL to discard)
 * @return SPI_OK on success
 */
spi_err_t spi_transfer32(spi_device_t device, uint32_t tx_word, uint32_t *rx);

/* ============================================================================
 * COMMAND + DATA HELPERS
 * Commonly used for displays and flash memory
 * ========================================================================== */

/**
 * @brief Send a command byte followed by data bytes (no CS release between)
 *
 * Sends command and data in a single CS assertion:
 *   CS LOW → cmd byte → data bytes → CS HIGH
 *
 * Used heavily by: display controllers (ST7735, ILI9341),
 *                  flash memory (W25Q128 page program)
 *
 * @param device    Device handle
 * @param cmd       Command byte
 * @param data      Data payload (NULL if len=0)
 * @param len       Number of data bytes after command
 * @return SPI_OK on success
 *
 * @example
 * @code
 * // ST7735: set column address range
 * uint8_t col_data[] = { 0x00, 0x00, 0x00, 0x7F };  // start=0, end=127
 * spi_write_cmd(display, 0x2A, col_data, 4);
 * @endcode
 */
spi_err_t spi_write_cmd(spi_device_t device, uint8_t cmd,
                         const uint8_t *data, size_t len);

/**
 * @brief Send a command byte and receive response bytes
 *
 * CS LOW → cmd byte → receive data bytes → CS HIGH
 *
 * Used by: flash memory (read ID, read data), ADCs (read conversion)
 *
 * @param device    Device handle
 * @param cmd       Command byte to send
 * @param[out] data Buffer for received bytes
 * @param len       Number of bytes to receive
 * @return SPI_OK on success
 *
 * @example
 * @code
 * // W25Q128: read JEDEC ID (3 bytes: manufacturer + device ID)
 * uint8_t id[3];
 * spi_read_cmd(flash, 0x9F, id, 3);
 * // id[0] = 0xEF (Winbond), id[1] = 0x40, id[2] = 0x18
 * @endcode
 */
spi_err_t spi_read_cmd(spi_device_t device, uint8_t cmd,
                        uint8_t *data, size_t len);

/* ============================================================================
 * DIAGNOSTICS
 * ========================================================================== */

/**
 * @brief Get current bus state
 */
spi_state_t spi_get_state(spi_bus_t bus);

/**
 * @brief Retrieve accumulated statistics
 */
spi_err_t spi_get_stats(spi_bus_t bus, spi_stats_t *stats);

/**
 * @brief Reset statistics counters
 */
spi_err_t spi_reset_stats(spi_bus_t bus);

/**
 * @brief Convert error code to human-readable string
 *
 * @example
 * @code
 * spi_err_t err = spi_write(device, buf, len);
 * if (err != SPI_OK) printf("SPI error: %s\n", spi_err_to_string(err));
 * @endcode
 */
const char *spi_err_to_string(spi_err_t err);

/**
 * @brief Get library version string
 */
const char *spi_version(void);

#ifdef __cplusplus
}
#endif

#endif /* SPI_H */
